apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "rabbitmq") | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "ims.selectorLabels" (dict "context" $ "component" "rabbitmq") | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.amqpPort }}
      targetPort: {{ .Values.rabbitmq.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
