apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-accounts-db
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "accounts-db") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.accountsDb.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-inventory-db
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "inventory-db") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.inventoryDb.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "api-gateway") | nindent 4 }}
type: Opaque
stringData:
  cert-password: {{ .Values.apiGateway.certPassword | quote }}
