apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-accounts-api
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "accounts-api") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" (dict "context" $ "component" "accounts-api") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-inventory-api
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "inventory-api") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" (dict "context" $ "component" "inventory-api") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "api-gateway") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" (dict "context" $ "component" "api-gateway") | nindent 6 }}
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: 30s
