<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="Quartz" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountsService.Domain\AccountsService.Domain.csproj" />
    <ProjectReference Include="..\AccountsService.Application\AccountsService.Application.csproj" />
    <ProjectReference Include="..\..\Shared.Kernel.AspNetCore\Shared.Kernel.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Shared.Kernel.EntityFrameworkCore\Shared.Kernel.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\Shared.Kernel.Redis\Shared.Kernel.Redis.csproj" />
    <ProjectReference Include="..\..\Shared.Kernel.Quartz\Shared.Kernel.Quartz.csproj" />
    <ProjectReference Include="..\..\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Options\" />
  </ItemGroup>

</Project>
