apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "ims.componentLabels" (dict "context" $ "component" "redis") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ims.selectorLabels" (dict "context" $ "component" "redis") | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "ims.selectorLabels" (dict "context" $ "component" "accounts-api") | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "ims.selectorLabels" (dict "context" $ "component" "inventory-api") | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "ims.selectorLabels" (dict "context" $ "component" "api-gateway") | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.redis.port }}
